From tomcat:slim

# Copy to images tomcat path 
ADD /ApiSoap/target/ApiSOAP-V100.war /usr/local/tomcat/webapps/ApiSOAP-V100.war

ADD /ApiRest/target/ApiREST-V100.war /usr/local/tomcat/webapps/ApiREST-V100.war