version: "3"
services:
    portainer:
        image: portainer/portainer
        container_name: "portainer-sd"
        command: -H unix:///var/run/docker.sock
        ports:
            - "9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
    tomcat:
        build: ./ApiSoap
        image: apisoap
        links:
          - loadbalancer-sd
        ports:
          - "8080:8080"
    loadbalancer-sd:
        build: ./ApiBanco/nginx
        image: "loadbalancer-sd"
        container_name: "loadbalancer-sd"
        links:
            - apiBanco-node1
            - apiBanco-node2
        ports:
            - "80:80"
    apiBanco-node1:
        build: ./ApiBanco/api
        image: apibanco
        container_name: "apiBanco-node1"
        environment:
            - MESSAGE=apiBanco-node1
        ports:
            - "4000"
        links:
            - mongo
        deploy:
            replicas: 2
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        healthcheck:
            test: curl -f http://172.18.0.4:4000/test || exit 1
            interval: 40s
            timeout: 20s
            retries: 3
    apiBanco-node2:
        build: ./ApiBanco/api
        image: apibanco
        container_name: "apiBanco-node2"
        environment:
            - MESSAGE=apiBanco-node2
        ports:
            - "4000"
        links:
            - mongo
        deploy:
            replicas: 2
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        healthcheck:
            test: curl -f http://172.18.0.5:4000/test || exit 1
            interval: 40s
            timeout: 20s
            retries: 3
    mongo:
        image: mongo
        volumes:
             - /data/mongodb/db:/data/db
        ports:
             - "27017:27017"
volumes:
    portainer_data:
