From tomcat:slim

# Copy to images tomcat path 
#ADD /api/src/main/webapp/WEB-INF/web.xml /usr/local/tomcat/conf/ 
ADD /api/target/ApiSOAP-V100.war /usr/local/tomcat/webapps/100.war

#ADD tomcat-users.xml /usr/local/tomcat/conf/
